//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class CITYREGION
    {
        public CITYREGION()
        {
            this.HOUSEREGIONLINKs = new HashSet<HOUSEREGIONLINK>();
        }
    
        public decimal ID { get; set; }
        public string NAME_ { get; set; }
        public string ADDRESS { get; set; }
        public Nullable<decimal> AMOUNTOFINHABITATS { get; set; }
        public Nullable<decimal> AREA { get; set; }
    
        public virtual ICollection<HOUSEREGIONLINK> HOUSEREGIONLINKs { get; set; }
    }
}
